name: dropout_predictor
description: Student Dropout Prediction App

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  file_picker: ^5.3.3
  fluttertoast: ^8.2.2
  flutter_dotenv: ^5.0.2   # Optional but recommended for API URLs

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0